// Domain-Event-Namen gemäß docs/architecture/02-module-boundaries.md §5.
// Payload-Typen entstehen mit den publizierenden Modulen; die Namen sind hier zentral,
// damit Publisher, Konsumenten und (später) Webhooks dieselbe Sprache sprechen.
export const DOMAIN_EVENTS = [
  'identity.user.registered',
  'identity.user.suspended',
  'identity.user.reactivated',
  'identity.user.deleted',
  'identity.login.succeeded',
  'identity.login.failed',
  'identity.session.revoked',
  'identity.mfa.enabled',
  'identity.mfa.disabled',
  'identity.mfa.recovery_code_used',
  'identity.provider.changed',
  'authorization.assignment.changed',
  'authorization.role.changed',
  'authorization.policy.changed',
  'authorization.group.changed',
  'knowledge.article.submitted',
  'knowledge.article.published',
  'knowledge.article.archived',
  'knowledge.article.deleted',
  'knowledge.review.completed',
  'knowledge.comment.created',
  'knowledge.comment.resolved',
  'knowledge.comment.deleted',
  'knowledge.feedback.given',
  'knowledge.space.visibility_changed',
  'translation.translation.submitted',
  'translation.translation.published',
  'translation.translation.outdated',
  'translation.translation.archived',
  'translation.review.completed',
  'organization.created',
  'organization.deleted',
  'organization.member.invited',
  'organization.member.joined',
  'organization.member.left',
  'organization.member.removed',
  'organization.team.changed',
  'repository.project.created',
  'repository.project.updated',
  'repository.project.deleted',
  'repository.sync.completed',
  'repository.sync.failed',
  'media.object.ready',
  'media.object.rejected',
  'media.object.deleted',
  'profile.achievement.awarded',
  'profile.reputation.changed',
  'configuration.settings.changed',
  'configuration.module.toggled',
  'configuration.setup.completed',
] as const;

export type DomainEventName = (typeof DOMAIN_EVENTS)[number];
